config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'index#index'

  resources :routines, :except => [:patch, :destroy]
  get 'publicroutines' => 'routines#publicroutines'
  get 'progress' => 'routines#currentroutine'
  get 'routine/:id' => 'routines#viewroutine', as: 'specroutine'
  patch 'setcurrent' => 'routines#setcurrent'
  get 'updateroutine/:id' => 'routines#viewupdateroutine', as: 'updateroutine'
  delete 'deleteroutine/:id' => 'routines#deleteroutine', as: 'deleteroutine'

end

app/models/routine.rb
class Routine < ActiveRecord::Base
	# belongs_to :user
  belongs_to :users
  # has_many :currently_on, :class_name => 'Users'
  # has_one :currently_using, :class_name => "User", :foreign_key => "currently_using_id"
	validates :name, presence: true
	validates :difficulty, presence: true
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_filter :ensure_loggedin!, except: [:publicroutines, :viewroutine]
  # add before_filter for ismine? as opposed to using if statement

  # i should eventually use routine_params once i figure out how to obtain json
  def routine_params
    params.require(:routine).permit(:name, :description, :difficulty)
  end

  def publicroutines
    if user_signed_in?
      @myroutines = current_user.routines
    end
    @sharedroutines = Routine.where(:shared => true)
  end

  def currentroutine
    # find a way to make associations work
    @current_routine = current_user.current_routine_id
    if @current_routine
      @progress = Routine.find(@current_routine)
    end
  end

  def new
    @routine = Routine.new
  end

  def viewroutine
    @specroutine = params['id']
    # first check if exists
    # then check if shared and current user 
    # then proceed

    @search = Routine.where(:id => @specroutine)
    if @search.length == 0
      flash[:notice] = "that does not exist"
      return redirect_to publicroutines_path
    end
    # elsif
    # @exists = current_user.routines.where(:id => @specroutine)
    if user_signed_in?
      if !@search[0].shared && ismine?(@specroutine)
        flash[:notice] = "you can't be there"
        return redirect_to root_path
      end
    end
    @specroutine = @search[0]
  end

  def viewupdateroutine
    @routineid = params['id']
    @ismine = ismine?(@routineid)
    @theroutine = Routine.where(:id => @routineid)
    if @theroutine.length == 0 || !@ismine
      flash[:notice] = "you cannot be here"
      redirect_to publicroutines_path
    end
    @theroutine = @theroutine[0]

  end

  # the update needs to be redone (it should use update attributes but instead it does the exact same thing as new)
  def update
    @routine = Routine.find(params['id'].to_i)
    @splitcount = params['routine']['tablecount'].split(",").map(&:to_i)
    @routine.name = params['routine']['name']
    @routine.description = params['routine']['description']
    @routine.difficulty = params['routine']['difficulty']
    @exerciselist = {}
    @exerciselist['split'] = @splitcount.length

    sum = 0
    alldays = []
    @splitcount.each do |rows|
      oneday = []
      rows.times do |i|
        oneexercise = [params['exercisename'][i+sum], params['sets'][i+sum], params['reps'][i+sum]]
        oneday << oneexercise
      end
      alldays << oneday
      sum = sum + rows
    end
    @exerciselist['list'] = alldays
    @routine.routine = @exerciselist
    # @current_user.routines << @routine
    if params['button'] == "Share & Set As Current"
      # puts "if button statement"
      @routine.shared = true
      if @routine.save
        @current_user.current_routine_id = @routine.id
        @current_user.save
        redirect_to specroutine_path(params['id'].to_i)
      end
    elsif params['button'] == "Share Routine"
      @routine.shared = true
      if @routine.save
        redirect_to specroutine_path(params['id'].to_i)
      end
    elsif params['button'] == "Set As Current"
      @routine.shared = false
      if @routine.save
        @current_user.current_routine_id = @routine.id
        @current_user.save
        redirect_to specroutine_path(params['id'].to_i)
      end
    end
  end

  def create
    # we won't use routine_params
    # routine_details = routine_params

    # example routine for reference
    # user.routines.create(name:'not current routine 6',description:'test text',shared:true, routine:{'split':2, 'list':[[['bench', 5,5],['rows', 3,8]],[['ohp',5,5],['deadlift',1,5]]]},difficulty:'novice')

    # example of what im doin
    # #<Routine id: 77, name: "10:18", description: "asd", routine: {"split"=>0, "list"=>[]}, created_at: "2016-11-19 13:18:33", updated_at: "2016-11-19 13:18:33", difficulty: "intermediate", user_id: 1, shared: true>

    # example post params for reference
    # Parameters: {"utf8"=>"✓", "routine"=>{"name"=>"", "description"=>"", "tablecount"=>"3,2"}, "exercisename"=>["1", "2", "3", "1", "2"], "sets"=>["1", "2", "3", "1", "2"], "reps"=>["1", "2", "3", "1", "2"], "commit"=>"Create"}

    @splitcount = params['routine']['tablecount'].split(",").map(&:to_i)
    @routine = Routine.new()
    @routine.name = params['routine']['name']
    @routine.description = params['routine']['description']
    @routine.difficulty = params['routine']['difficulty']

    @exerciselist = {}
    @exerciselist['split'] = @splitcount.length

    sum = 0
    alldays = []
    @splitcount.each do |rows|
      oneday = []
      rows.times do |i|
        oneexercise = [params['exercisename'][i+sum], params['sets'][i+sum], params['reps'][i+sum]]
        oneday << oneexercise
      end
      alldays << oneday
      sum = sum + rows
    end
    @exerciselist['list'] = alldays
    @routine.routine = @exerciselist
    @current_user.routines << @routine
    if params['button'] == "Share & Set As Current"
      # puts "if button statement"
      @routine.shared = true
      if @routine.save
        @current_user.current_routine_id = @routine.id
        @current_user.save
        redirect_to action: 'currentroutine'
      end
    elsif params['button'] == "Share Routine"
      @routine.shared = true
      if @routine.save
        redirect_to action: 'publicroutines'
      end
    elsif params['button'] == "Set As Current"
      @routine.shared = false
      if @routine.save
        @current_user.current_routine_id = @routine.id
        @current_user.save
        redirect_to action: 'currentroutine'
      end
    end
    # dont forget to delete currentroutine if it isnt shared and user chooses to set current
  end

  # move this to users controller later
  def setcurrent
    # current_user.current_routine_id = params['routine_id']

    # this is redesigned way 
    # puts params
    copyroutine = Routine.find(params['routine_id'])
    puts copyroutine.inspect
    #<Routine id: 1, name: "stronglift 5x5 v2", description: "one of the more popular beginner programs", 
    # routine: {"list"=>[[["bench press", "5", "5"], ["bent over rows", "3", "10"], ["chest press", "3", "5"]], [["over head press", "5", "5"], ["deadlift", "3", "5"], ["lat pulldown", "3", "8"], ["bench press", "3", "10"]]], "split"=>2}, 
    # created_at: "2016-11-18 02:36:33", updated_at: "2016-12-02 05:26:31", difficulty: "novice", user_id: 1, shared: true>
    if ismine?(params['routine_id'])
      current_user.current_routine_id = copyroutine
      if current_user.save
        redirect_to progress_path
      end
    else
      setcur = Routine.new()
      setcur.name = copyroutine.name
      setcur.description = copyroutine.description
      setcur.routine = copyroutine.routine
      setcur.difficulty = copyroutine.difficulty
      setcur.shared = false
      if setcur.save
        @current_user.routines << setcur
        @current_user.current_routine_id = setcur.id
        @current_user.save
        redirect_to progress_path
      end
    end
    
    # this is end of redesigned way

    # if current_user.save
    #   redirect_to progress_path
    # end
  end

  def deleteroutine
    chosenroutine = params['routine_id']
    if ismine?(chosenroutine)
      if Routine.find(chosenroutine).destroy
        redirect_to publicroutines_path
      end
    else
      # not yet decided what to do if user somehow tries to delete a routine that isnt theirs
      redirect_to publicroutines_path
    end
  end

  def ismine?(routineid)
    return current_user.routines.where(:id => routineid).length == 1
  end
  private
  def ensure_loggedin!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/routines_helper.rb
module RoutinesHelper
end

app/views/routines/_dayform.html.erb
<!-- workout form -->
  <div class="routineform">
    <table class="table auto">
      <thead class="thead-inverse">
        <th>Exercise</th>
        <th>sets</th>
        <th>reps</th>
        <th class="text-right" onclick="removetable($(this))"><div class='glyphicon glyphicon-remove'></div></th>
      </thead>
      <tbody>
        <%= render 'exerciseform' %>
        <%= render 'exerciseform' %>
        <tr class="addexercisebutton"><td><a href="javascript:;" onclick="addexercise($(this))">Add exercise</a></td></tr>
      </tbody>
    </table>
  </div>

app/views/routines/_exerciseform.html.erb
<tr>
  <td class="col-xs-8">
    <%= text_field_tag "exercisename[]", nil, class: "form-control", :required => true %>
  </td>
  <td class="col-xs-2">
    <%= number_field_tag "sets[]", nil, class: "form-control", :required => true %>
  </td>
  <td class="col-xs-2">
    <%= number_field_tag "reps[]", nil, class: "form-control", :required => true %>
  </td>
  <td class="text-right" onclick="removeexercise($(this))"><div class='glyphicon glyphicon-remove'></div></td>
</tr>

app/views/routines/currentroutine.html.erb
<div class="container">
<p>
  <% if !@progress.nil? %>
    
    <div class="btn-group pull-right">
      <button class="btn btn-default btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        settings <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <!-- <li><a href="#" class="dropdown-item">edit</a></li> -->
        <li><%= link_to 'edit', updateroutine_path(@current_routine), :class => "dropdown-item" %></li>
        <li><%= link_to('new', new_routine_path, :class => "dropdown-item", :method => :get) %></li>
      </ul>
    </div>


    <h3><%= @progress.name %><br></h3>
    <h4> <%= @progress.difficulty %> <br> </h4>
    <h5>
      <%= @progress.description %> <br>
    </h5>
    <% @progress.routine['list'].each do |day| %>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>name</th>
              <th>sets</th>
              <th>reps</th>
            </tr>
          </thead>
          <tbody>
            <% day.each do |exerc| %>
              <tr>
                <td class='col-sm-8'><%= exerc[0] %></td>
                <td class='col-sm-2'><%= exerc[1] %></td>
                <td class='col-sm-2'><%= exerc[2] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

  <% else %>
    <h1>
      looks like you are not on a program
    </h1>
    <h3>
      <%= link_to('click here to create a routine', new_routine_path, :method => :get) %><br>
      <%= link_to('click here to browse shared routines', publicroutines_path, :method => :get) %>
    </h3>
  <% end %>
</p>
</div>

app/views/routines/new.html.erb
<div class='container'>
<h1>create a routine</h1>
  <%= form_for @routine, :remote => true, :format => :json do |f| %>

    <!-- routine name textfield -->
    <div class="row">
      <div class="form-group col-xs-4">
        <%= label_tag :name, "Name of routine", :class => "control-label" %><br>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>

    <!-- description textarea -->
    <div class="row no-margin">
      <div class="form-group">
        <%= label_tag :description, "Description" %>
        <%= f.text_area :description, :class => "form-control", :rows => 8 %>
      </div>
    </div>

    <!-- radio for difficulty -->
    <div class="row no-margin">
      <label class="custom-control custom-radio">
        <%= f.radio_button :difficulty, "novice", :class=>"custom-control-input" %>
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">Novice</span>
      </label>
      <br>
      <label class="custom-control custom-radio">
        <%= f.radio_button :difficulty, "intermediate", :class=>"custom-control-input" %>
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">Intermediate</span>
      </label>
      <br>
      <label class="custom-control custom-radio">
        <%= f.radio_button :difficulty, "advanced", :class=>"custom-control-input" %>
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">Advanced</span>
      </label>
    </div>
    <br>

    <!-- workout form -->

    <div id="workoutforms" class="row no-margin">
      <a href="javascript:;" onclick="addday($(this))">Add day</a>
      <%= render 'dayform' %>
      <%= render 'dayform' %>
    </div>
 
    <!-- hidden form for table and row count -->
    <!-- <div> -->
      <%= f.hidden_field(:tablecount, :value => []) %> 
    <!-- </div> -->
    <!-- submit button -->
    <div class="row no-margin">
      <%= f.submit "Set As Current", :name => "button", :value => "Set As Current", :class => "btn btn-default" %>
      <%= f.submit "Share Routine", :name => "button", :value => "Share Routine", :class => "btn btn-default" %>
      <%= f.submit "Share & Set As Current", :name => "button", :value => "Share & Set As Current", :class => "btn btn-default" %>
    </div>

  <% end %>


  <div style="display: none;">
    <table>
      <tbody id="newexerciseform">
        <%= render "exerciseform" %>
      </tbody>
    </table>
  </div>

  <div id="newdayform" style="display:none;">
    <%= render "dayform" %>
  </div>
</div>

app/views/routines/publicroutines.html.erb
<div class="col-sm-2">
  <nav class="nav-sidebar">
    <ul class="nav tabs visible-large">
      <li class="active"><a href="#tab1" data-toggle="tab">All Public</a></li>
      <li class=""><a href="#tab2" data-toggle="tab">My Shared</a></li>
      <li class=""><%= link_to("Create New", new_routine_path, :method => :get) %></li>
    </ul>
  </nav>
</div>
  <!-- tab content -->
<div class="container">
  <div class="tab-content">
    <div class="tab-pane active text-style" id="tab1">
      <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <!-- Saved Exercises -->
              <th>
              name
              </th>
              <th>
              difficulty
              </th>
            </thead>
            <tbody>
              <% @sharedroutines.each do |allroutines| %>
                <tr>
                <td>
                <%= link_to(allroutines.name, specroutine_path(allroutines.id), :method => :get) %>
                </td>
                <td>
                <%= allroutines.difficulty %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>


    <div class="tab-pane text-style" id="tab2">
      <% if user_signed_in? && !(@myroutines.length == 0) %>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>
              name
              </th>
              <th>
              difficulty
              </th>
              <th>
              shared?
              </th>
              </tr>
            </thead>
            <tbody>
              <% @myroutines.each do |allroutines| %>
                <tr>
                <td>
                <%= link_to(allroutines.name, specroutine_path(allroutines.id), :method => :get) %>
                </td>
                <td>
                <%= allroutines.difficulty %>
                </td>
                <td>
                <%= allroutines.shared %>
                </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <%= link_to('click here to create a routine to share', new_routine_path, :method => :get) %>  
      <% end %>
    </div>

  </div>
</div>

app/views/routines/viewroutine.html.erb
<div class="container">
  <div class="btn-group pull-right">
    <button class="btn btn-default btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      settings <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% if @ismine %>
        <li><%= link_to 'edit', updateroutine_path(@specroutine.id), :class => "dropdown-item" %></li>
        <li><%= link_to 'delete', '', :class => "dropdown-item", :onclick => "$('#deletecurrent').submit()" %></li>
      <% end %>
      <li><%= link_to 'set as current', '', :class => "dropdown-item", :onclick => "$('#settcurrent').submit()" %></li>
    </ul>
  </div>
  <h3><%= @specroutine.name %><br></h3>
  <h4> <%= @specroutine.difficulty %> <br> </h4>
  <h5>
    <%= @specroutine.description %> <br>
  </h5>


  <% @specroutine.routine['list'].each do |day| %>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>name</th>
            <th>sets</th>
            <th>reps</th>
          </tr>
        </thead>
        <tbody>
          <% day.each do |exerc| %>
            <tr>
              <td class='col-sm-8'><%= exerc[0] %></td>
              <td class='col-sm-2'><%= exerc[1] %></td>
              <td class='col-sm-2'><%= exerc[2] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

  <div style="display: none;">
  <%= form_tag setcurrent_path, :id => "settcurrent", :method => :patch do %>
    <%= hidden_field_tag :routine_id, @specroutine.id %>
  <% end %>
  <%= form_tag deleteroutine_path, :id => "deletecurrent", :method => :delete do %>
    <%= hidden_field_tag :routine_id, @specroutine.id %>
  <% end %>
  </div>
</div>

app/views/routines/viewupdateroutine.html.erb
<div class="container">
<h3> Editing "<%= @theroutine.name %>" </h3>
<%= form_for @theroutine, :remote => true, :format => :json do |f|%>
  <!-- routine name textfield -->
  <div class="row">
    <div class="form-group col-xs-4">
      <%= label_tag :name, "Name of routine", :class => "control-label" %><br>
      <%= f.text_field :name, :value => @theroutine.name, :class => "form-control" %>
    </div>
  </div>

  <!-- description textarea -->
  <div class="row no-margin">
    <div class="form-group">
      <%= label_tag :description, "Description" %>
      <%= f.text_area :description, :value => @theroutine.description, :class => "form-control", :rows => 8 %>
    </div>
  </div>

  <!-- radio for difficulty -->
  <div class="row no-margin">
    <label class="custom-control custom-radio">
      <%= f.radio_button :difficulty, "novice", :checked => (@theroutine.difficulty == "novice"), :class=>"custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Novice</span>
    </label>
    <br>
    <label class="custom-control custom-radio">
      <%= f.radio_button :difficulty, "intermediate", :checked => (@theroutine.difficulty == "intermediate"), :class=>"custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Intermediate</span>
    </label>
    <br>
    <label class="custom-control custom-radio">
      <%= f.radio_button :difficulty, "advanced", :checked => (@theroutine.difficulty == "advanced"), :class=>"custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Advanced</span>
    </label>
  </div>
  <br>
  <div id="workoutforms" class="row no-margin">
    <a href="javascript:;" onclick="addday($(this))">Add day</a>
    <% @theroutine.routine['list'].each do |day| %>
      <div class="routineform">
        <table class="table auto">
          <thead class="thead-inverse">
            <th>Exercise</th>
            <th>sets</th>
            <th>reps</th>
            <th class="text-right" onclick="removetable($(this))"><div class='glyphicon glyphicon-remove'></div></th>
          </thead>
          <tbody>
            <% day.each do |exer| %>
              <tr>
                <td class="col-xs-8">
                  <%= text_field_tag "exercisename[]", exer[0], class: "form-control", :required => true %>
                </td>
                <td class="col-xs-2">
                  <%= number_field_tag "sets[]", exer[1], class: "form-control", :required => true %>
                </td>
                <td class="col-xs-2">
                  <%= number_field_tag "reps[]", exer[2], class: "form-control", :required => true %>
                </td>
                <td class="text-right" onclick="removeexercise($(this))"><div class='glyphicon glyphicon-remove'></div></td>
              </tr>
            <% end %>
            <tr class="addexercisebutton"><td><a href="javascript:;" onclick="addexercise($(this))">Add exercise</a></td></tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>

  <%= f.hidden_field(:tablecount, :value => []) %> 
  <div class="row no-margin">
    <%= f.submit "Set As Current", :name => "button", :value => "Set As Current", :class => "btn btn-default" %>
    <%= f.submit "Share Routine", :name => "button", :value => "Share Routine", :class => "btn btn-default" %>
    <%= f.submit "Share & Set As Current", :name => "button", :value => "Share & Set As Current", :class => "btn btn-default" %>
  </div>
<% end %>
  <div style="display: none;">
    <table>
      <tbody id="newexerciseform">
        <%= render "exerciseform" %>
      </tbody>
    </table>
  </div>

  <div id="newdayform" style="display:none;">
    <%= render "dayform" %>
  </div>

  <%= hidden_field_tag 'routineid', @theroutine.id %>
</div>