config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'index#index'

  resources :routines, :except => [:patch, :destroy]
  get 'publicroutines' => 'routines#publicroutines'
  get 'progress' => 'routines#currentroutine'
  get 'routine/:id' => 'routines#viewroutine', as: 'specroutine'
  patch 'setcurrent' => 'routines#setcurrent'
  get 'updateroutine/:id' => 'routines#viewupdateroutine', as: 'updateroutine'
  delete 'deleteroutine/:id' => 'routines#deleteroutine', as: 'deleteroutine'

end

app/views/index/index.erb
<div class="masthead">
<h2>
  Routineapp<br>
</h2>
<h3>
  A simple tool to monitor your progress 
  <br>
  I need a big logo so the black thing
  <br>
  doesn't look so small
</h3>

</div>
<div class="container index-container">
<h3>
  <%= link_to("Create your own routine", new_routine_path, :method => :get) %>
</h3>
  <h4> If you are currently on a specialized routine, <br>you can create a routine and start monitoring <br>your progress here. If you'd like, you can also share <br>your routine with others </h4>
  <br><br>
  or 
  <br><br>
<h3>
  <%= link_to("Choose from a list of publicly shared routines", publicroutines_path, :method => :get) %>
</h3>
  <h4>
  If you are currently not on a routine, you can choose <br>from many routines that have been shared by others
  </h4>
  <br><br>
  and 
  <br><br>
<h3>
  <%= link_to("Monitor your progress", progress_path, :method => :get) %><br>
</h3>
  <h4>
  already a member? <br>
  monitor your progress
  </h4>
</div>